---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: emeraldsquad/concourse
 
inputs:
  - name: version
  - name: git-repo
  
outputs:
  - name: gh
  - name: pushme
  - name: notifications

run:
  path: git-repo/ci/scripts/create-release